% penetration_depth.m
% Generates Figure 2 using data generated by Tb_data.mat for the
% publication
% 
% Wolfenbarger, N. S., Broome, A. L., Schroeder, D. M., Ermakov, A. I.,
% Bolton, S. J., and Blankenship, D. D. (2025). Passive Microwave
% Radiometry and Active Radar Sounding as Complementary Tools for
% Geophysical Investigations of Icy Ocean Worlds.

clear all; close all; clc

%% Add Paths
% Located at https://github.com/nwolfenb
addpath(genpath('..\..\IcyRF'))
addpath(genpath('..\..\BrineVolumeFraction'))

%% Defaults
fontsize = 8;
linewidth = 2;
interpreter = 'latex';
% brewermap available at MATLAB File Exchange
colors = brewermap(10,'Spectral');

%% Inputs
rho = 940;
g = 1.315;
D = logspace(0,3); 
Ts = 100;
N = 1e4;

%% Temperature
figure
subplot(2,2,1)
Tm = 270;
b = 1;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax1 = gca;
ax1.TickLabelInterpreter = interpreter;
ax1.YDir = 'reverse';
ax1.FontSize = fontsize;
ax1.XTick = [Ts Tm];
ax1.XTickLabel = {'$100$';'$f(D)$'};
ax1.XLabel.String = 'Temperature, $T$ (K)';
ax1.XLabel.FontSize = fontsize;
ax1.XLabel.Interpreter = interpreter;
ax1.YLabel.String = 'Fractional Depth, $z/D$';
ax1.YLabel.FontSize = fontsize;
ax1.YLabel.Interpreter = interpreter;
ax1.XLim = [Ts-50 Tm+50];
ax1.YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

%% Attenuation Rate
f = [0.009 0.06 0.6 1.2 2.5 5.0 10 22]'*1e9;
subplot(2,2,2)
for m = 1:length(f)
    T = linspace(100,273.15);
    eps_ice = ice_permittivity(T-273.15,f(m),0);
    [alpha, Na] = EMalpha(eps_ice,f(m));
    semilogy(T,Na*1e3,'Color',colors(m,:),'LineWidth',linewidth)
    hold on
end
ax2 = gca;
ax2.TickLabelInterpreter = interpreter;
ax2.FontSize = fontsize;
ax2.XLabel.String = 'Temperature, $T$ (K)';
ax2.XLabel.FontSize = fontsize;
ax2.XLabel.Interpreter = interpreter;
ax2.YLabel.String = 'Attenuation Rate, $N_{\alpha}$ (dB/km)';
ax2.YLabel.FontSize = fontsize;
ax2.YLabel.Interpreter = interpreter;
ax2.XLim = [100 273.15];
ax2.YLim = [1e-3 1e3];

leg2 = legend(ax2,cellstr(num2str(f/1e9)),'Location','EastOutside');
leg2.Title.String = '$f$ (GHz)';
leg2.FontSize = fontsize;
leg2.ItemTokenSize = [15 15];
leg2.Interpreter = interpreter;



%% Radiometer "Penetration Depth"
load('Tb_log.mat');

subplot(2,2,3)
crit = 0.2;
for m = 1:length(f)
    for n = 1:length(D)
        z = Z{m,n};
        if any(Tb_z{m,n}<crit)
            delta(n) = min(z(Tb_z{m,n}<crit));
        else
            delta(n)=D(n);
        end
    end

    semilogx(D/1e3,100*delta./D,'Color',colors(m+2,:),'LineWidth',linewidth)
    hold on

end

att_crit = -10*log10(1/exp(1));
for m = 1:length(f)
    P = rho*g*D;
    Tm = Tmelt(P);

    z = linspace(0,1,N)';
    z = z*D;
    T = Ts*(Tm/Ts).^(z./D);


    eps_ice = ice_permittivity(T-273.15,f(m),0);
    [alpha, Na] = EMalpha(eps_ice,f(m));

    for n = 1:length(D)
        att = cumtrapz(z(:,n),Na(:,n));
        delta(n) = max(z(att<=att_crit,n));
    end

    semilogx(D/1e3,100*delta./D,':','Color',colors(m+2,:),'LineWidth',linewidth)
    hold on

end

ax3 = gca;
ax3.TickLabelInterpreter = interpreter;
ax3.FontSize = fontsize;
ax3.XLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax3.XLabel.FontSize = fontsize;
ax3.XLabel.Interpreter = interpreter;
ax3.YLabel.String = 'Penetration Depth, $\delta_p$ (\%)';
ax3.YLabel.FontSize = fontsize;
ax3.YLabel.Interpreter = interpreter;
ax3.Title.String = '$Passive$ Radiometer';
ax3.Title.FontSize = fontsize;
ax3.Title.Interpreter = interpreter;
ax3.XLim = [min(D) max(D)]/1e3;
ax3.XTick = logspace(0,5,6)/1e3; 

%% Radar "Penetration Depth"
f = [0.009 0.06]'*1e9;
S = [50 40 30];
subplot(2,2,4)
for p = 1:length(S)
    for m = 1:length(f)
        P = rho*g*D;
        Tm = Tmelt(P);

        z = linspace(0,1,N)';
        z = z*D;
        T = Ts*(Tm/Ts).^(z./D);


        eps_ice = ice_permittivity(T-273.15,f(m),0);
        [alpha, Na] = EMalpha(eps_ice,f(m));

        for n = 1:length(D)
            att = 2*cumtrapz(z(:,n),Na(:,n));
            SNR = S(p)-att;
            delta(n) = max(z(SNR>0,n));
        end

        if m == 1
            ps(p) = semilogx(D/1e3,100*delta./D,'Color',colors(m,:),'LineWidth',linewidth/p);
            hold on
        else
            semilogx(D/1e3,100*delta./D,'Color',colors(m,:),'LineWidth',linewidth/p);
        end
    end
end

D = logspace(-3,2,1e4)*1e3;
att_crit = -10*log10(1/exp(1));
for m = 1:length(f)
    P = rho*g*D;
    Tm = Tmelt(P);

    z = linspace(0,1,N)';
    z = z*D;
    T = Ts*(Tm/Ts).^(z./D);


    eps_ice = ice_permittivity(T-273.15,f(m),0);
    [alpha, Na] = EMalpha(eps_ice,f(m));

    for n = 1:length(D)
        att = cumtrapz(z(:,n),Na(:,n));
        delta(n) = max(z(att<=att_crit,n));
    end

    semilogx(D/1e3,100*delta./D,':','Color',colors(m,:),'LineWidth',linewidth)
    hold on

end

ax4 = gca;
ax4.TickLabelInterpreter = interpreter;
ax4.FontSize = fontsize;
ax4.XLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax4.XLabel.FontSize = fontsize;
ax4.XLabel.Interpreter = interpreter;
ax4.YLabel.String = 'Penetration Depth, $\delta_p$ (\%)';
ax4.YLabel.FontSize = fontsize;
ax4.YLabel.Interpreter = interpreter;
ax4.Title.String = '$Active$ Radar';
ax4.Title.FontSize = fontsize;
ax4.Title.Interpreter = interpreter;
ax4.XLim = [min(D) max(D)]/1e3;
ax4.XTick = logspace(0,5,6)/1e3; 
ax4.XTickLabelRotation = 0;

leg4 = legend(ps,cellstr(num2str(S')),'Location','EastOutside');
leg4.Title.String = '$S^*$ (dB)';
leg4.FontSize = fontsize;
leg4.ItemTokenSize = [15 15];
leg4.Interpreter = interpreter;

%% Figure Formatting
% units
ax1.Units = 'centimeters';
ax2.Units = 'centimeters';
ax3.Units = 'centimeters';
ax4.Units = 'centimeters';
leg2.Units = 'centimeters';
leg4.Units = 'centimeters';

% left
margin = 1;
ax1.Position(1) = margin;
ax3.Position(1) = margin;

% height
h0 = 4.25;
ax1.Position(4) = h0;
ax2.Position(4) = h0;
ax3.Position(4) = h0;
ax4.Position(4) = h0;

% width
w0 = 4.25;
ax1.Position(3) = w0;
ax2.Position(3) = w0;
ax3.Position(3) = w0;
ax4.Position(3) = w0;

% bottom
ax3.Position(2) = margin;
ax4.Position(2) = margin;
ax1.Position(2) = ax3.Position(2)+ax1.Position(4)+1.5*margin;
ax2.Position(2) = ax4.Position(2)+ax2.Position(4)+1.5*margin;

% left
ax2.Position(1) = ax1.Position(1)+ax2.Position(3)+1.5*margin;
ax4.Position(1) = ax3.Position(1)+ax4.Position(3)+1.5*margin;

% legends
leg2.Position(1) = ax2.Position(1)+ax2.Position(3)+0.5*margin;
leg4.Position(1) = ax4.Position(1)+ax4.Position(3)+0.5*margin;

% labels
ta = annotation('textbox');
ta.String = 'a';
ta.FontSize = fontsize+2;
ta.FontWeight = 'bold';
ta.Interpreter = 'tex';
ta.Units = 'centimeters';
ta.Position = [ax1.Position(1)-1.1*margin ax1.Position(2)+h0 0.1 0.1];
ta.EdgeColor = 'w';
ta.HorizontalAlignment = 'left';
ta.VerticalAlignment = 'bottom';

tb = annotation('textbox');
tb.String = 'b';
tb.FontSize = fontsize+2;
tb.FontWeight = 'bold';
tb.Interpreter = 'tex';
tb.Units = 'centimeters';
tb.Position = [ax2.Position(1)-1.1*margin ax2.Position(2)+h0 0.1 0.1];
tb.EdgeColor = 'w';
tb.HorizontalAlignment = 'left';
tb.VerticalAlignment = 'bottom';

tc = annotation('textbox');
tc.String = 'c';
tc.FontSize = fontsize+2;
tc.FontWeight = 'bold';
tc.Interpreter = 'tex';
tc.Units = 'centimeters';
tc.Position = [ax3.Position(1)-1.1*margin ax3.Position(2)+h0 0.1 0.1];
tc.EdgeColor = 'w';
tc.HorizontalAlignment = 'left';
tc.VerticalAlignment = 'bottom';

td = annotation('textbox');
td.String = 'd';
td.FontSize = fontsize+2;
td.FontWeight = 'bold';
td.Interpreter = 'tex';
td.Units = 'centimeters';
td.Position = [ax4.Position(1)-1.1*margin ax4.Position(2)+h0 0.1 0.1];
td.EdgeColor = 'w';
td.HorizontalAlignment = 'left';
td.VerticalAlignment = 'bottom';

f = gcf;
f.Color = 'w';
f.Units = 'centimeters';
width = 2*(2.25*margin+w0);
height = 2*(1.5*margin+h0);
f.Position(3:4) = [width height];
