% radar_constraints.m
% Generates Figure 5 using data generated by Tb_data.mat for the
% publication
%
% Wolfenbarger, N. S., Broome, A. L., Schroeder, D. M., Ermakov, A. I.,
% Bolton, S. J., and Blankenship, D. D. (2025). Passive Microwave
% Radiometry and Active Radar Sounding as Complementary Tools for
% Geophysical Investigations of Icy Ocean Worlds.

clear all; close all; clc

%% Add Paths
% Located at https://github.com/nwolfenb
addpath(genpath('..\..\IcyRF'))

%% Defaults
fontsize = 8;
linewidth = 2;
interpreter = 'latex';

%% Constants
att_vec = logspace(-1,1,1000);

f = 9e6;
D = 1e3; % m
dz = 1;
z = (0:dz:D)';
Ts = 100;
Tm0 = 273;

Tr = 251; % Reference temperature (K)
k = 8.617332e-5; % Boltzmann constant (eV/K)
CM_Cl = 0.5;
Ea_Cl = 0.19;

%% Idealized Ice Shell
T = Ts*(Tm0/Ts).^(z/D);
eps_ice = ice_permittivity(T-273.15,f,0);

[alpha, Na] = EMalpha(eps_ice,f);
att= 2e3*Na;
z_D = z/D;

z_D_vec = interp1(att,z_D,att_vec);

%% Freezing Point Depression
% Temperature Profile
p = 4;
subplot(3,3,p)
N = 1e4;
Tm = 250;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$273-\Delta T_f$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

% Attenuation Rate
p = 5;
subplot(3,3,p)
load('Tb_deltaTm.mat','deltaTm')
dz = 1;
z = (0:dz:D)';
att = zeros(length(z),length(deltaTm));
for q = 1:length(deltaTm)
    Tm = Tm0-deltaTm(q);

    T = Ts*(Tm/Ts).^(z/D);
    eps_ice = ice_permittivity(T-273.15,f,0);

    [alpha, Na] = EMalpha(eps_ice,f);
    att(:,q) = 2e3*Na;

end

x = repmat(deltaTm,length(z),1);
y = repmat(z/1e3,1,length(deltaTm));

[C,h] = contour(x,y,att,[1e-1 1e0 1e1 1e2],'LineWidth',linewidth,'LineColor',[255 0 0]/255);

ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Freezing Point Depression, $\Delta T_f$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$2N_{\alpha}$ (dB/km)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
ax(p).Layer = 'top';
ax(p).XTick = 0:20:100;

clabel(C,h,'manual','Interpreter','latex','FontSize',fontsize,'Color',[255 0 0]/255,...
    'BackgroundColor','w')

% Compatible Ice Shell Thickness
p = 6;
subplot(3,3,p)
z_D = z/D;
C = contourc(deltaTm,z_D,att,att_vec);
S = contourdata(C);

for n = 1:length(S)
    semilogx(S(n).level*ones(size(S(n).ydata)),S(n).ydata,'Color',0.8*[1 1 1])
    hold on
end

h = plot(att_vec,z_D_vec,'Color',[255 0 0]/255,'LineWidth',linewidth);
leg = legend(h,'$\Delta T_f=0$ K');
leg.Location = 'NorthEast';
leg.ItemTokenSize = [15 15];
leg.FontSize = fontsize;
leg.Interpreter = interpreter;

ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Two-Way Attenuation Rate, $2N_{\alpha}$ (dB/km)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).YLim = [0 1];
ax(p).Layer = 'Top';

%% Convective Layer

% Temperature Profile
p = 1;
subplot(3,3,p)
Tm = 260;
N = 1e4/2;
z = linspace(0,1/2,N)';
T = Ts*(Tm/Ts).^(z/(1/2));
z = [z; linspace(1/2,1,N)'];
z = flipud(z);
T = [T; ones(size(T))*Tm];

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$260$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];
ax(p).YTick = [0 1];
ax(p).YTickLabel = cellstr(num2str(([1 0])'));

t1 = text(Ts,1,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,1,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

delta_x = 15;
delta_y = 0.025;

ar = annotation('doublearrow');
ar.Parent = ax(p);
ar.X = [Tm-delta_x Tm-delta_x];
ar.Y = [0+delta_y 0.5-delta_y];
ar.Head1Length = 5;
ar.Head2Length = 5;
ar.Head1Width = 5;
ar.Head2Width = 5;
ar.Head1Style = 'plain';
ar.Head2Style = 'plain';
ar.LineWidth = linewidth/2;

txt = text(Tm-delta_x,0.25,'$d_{conv}/D$ ');
txt.FontSize = fontsize;
txt.HorizontalAlignment = 'right';
txt.Interpreter = interpreter;

% Attenuation Rate
p = 2;
subplot(3,3,p)
load('Tb_fconv_260.mat','fconv')
dz = 1;
z = (0:dz:D)';
att = zeros(length(z),length(fconv));
for q = 1:length(fconv)
    
    T = zeros(size(z));
    dconv = D*fconv(q);
    dcond = D - dconv;
    T(z<=dcond) = Ts*(Tm/Ts).^(z(z<=dcond)./dcond);
    T(z>dcond) = Tm;

    eps_ice = ice_permittivity(T-273.15,f,0);

    [alpha, Na] = EMalpha(eps_ice,f);
    att(:,q) = 2e3*Na;

end

x = repmat(fconv,length(z),1);
y = repmat(z/1e3,1,length(fconv));

[C,h] = contour(x,y,att,[1e-1 1e0 1e1 1e2],'LineWidth',linewidth,'LineColor',[255 0 0]/255);

ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String =  'Convective Fraction, $d_{conv}/D$';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$2N_{\alpha}$ (dB/km)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
ax(p).XTick = [0:.2:1];

clabel(C,h,'manual','Interpreter','latex','FontSize',fontsize,'Color',[255 0 0]/255,...
    'BackgroundColor','w')

% Compatible Ice Shell Thickness
p = 3;
subplot(3,3,p)
z_D = z/D;
C = contourc(fconv,z_D,att,att_vec);
S = contourdata(C);

for n = 1:length(S)
    semilogx(S(n).level*ones(size(S(n).ydata)),S(n).ydata,'Color',0.8*[1 1 1])
    hold on
end

h = plot(att_vec,z_D_vec,'Color',[255 0 0]/255,'LineWidth',linewidth);
leg = legend(h,'$d_{conv}=0$, $T_m=273$ K');
leg.Location = 'NorthEast';
leg.ItemTokenSize = [15 15];
leg.FontSize = fontsize;
leg.Interpreter = interpreter;

ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Two-Way Attenuation Rate, $2N_{\alpha}$ (dB/km)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).YLim = [0 1];
ax(p).Layer = 'Top';

%% Chloride-Doped Ice
% Temperature Profile
p = 7;
subplot(3,3,p)
N = 1e4;
Tm = Tm0;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$273$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

% Attenuation Rate
p = 8;
subplot(3,3,p)
load('Tb_Cl.mat','uMCl')
dz = 1;
z = (0:dz:D)';
att = zeros(length(z),length(uMCl));
for q = 1:length(uMCl)
    C_Cl = uMCl(q)*CM_Cl;

    T = Ts*(Tm/Ts).^(z./D);

    sigma_Cl = C_Cl.*exp(-(Ea_Cl/k).*((1./T)-(1/Tr)))/1e6;

    eps_ice = ice_permittivity(T-273.15,f,sigma_Cl);

    [alpha, Na] = EMalpha(eps_ice,f);
    att(:,q) = 2e3*Na;

end

x = repmat(uMCl,length(z),1);
y = repmat(z/1e3,1,length(uMCl));

[C,h] = contour(x,y,att,[1e-1 1e0 1e1 1e2],'LineWidth',linewidth,'LineColor',[255 0 0]/255);

ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Ice Chlorinity, [Cl$^{-}$] ($\mu$M)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$2N_{\alpha}$ (dB/km)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
ax(p).XTick = [0:50:300];

clabel(C,h,'manual','Interpreter','latex','FontSize',fontsize,'Color',[255 0 0]/255,...
    'BackgroundColor','w')


% Compatible Ice Shell Thickness
p = 9;
subplot(3,3,p)
z_D = z/D;
C = contourc(uMCl,z_D,att,att_vec);
S = contourdata(C);

for n = 1:length(S)
    semilogx(S(n).level*ones(size(S(n).ydata)),S(n).ydata,'Color',0.8*[1 1 1])
    hold on
end

h = plot(att_vec,z_D_vec,'Color',[255 0 0]/255,'LineWidth',linewidth);
leg = legend(h,'[Cl$^{-}]=0$ $\mu$M');
leg.Location = 'NorthEast';
leg.ItemTokenSize = [15 15];
leg.FontSize = fontsize;
leg.Interpreter = interpreter;


ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Two-Way Attenuation Rate, $2N_{\alpha}$ (dB/km)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).YLim = [0 1];
ax(p).Layer = 'Top';

%% Figure Formatting
% units
for p = 1:length(ax)
ax(p).Units = 'centimeters';
end

% left
margin = 1;
ax(1).Position(1) = 1.5*margin;
ax(4).Position(1) = 1.5*margin;
ax(7).Position(1) = 1.5*margin;

% height
h0 = 4.25;
for p = 1:length(ax)
ax(p).Position(4) = h0;
end

% width
w0 = 4.25;
for p = 1:length(ax)
ax(p).Position(3) = w0;
end

% bottom
ax(7).Position(2) = margin;
ax(8).Position(2) = margin;
ax(9).Position(2) = margin;
ax(4).Position(2) = ax(7).Position(2)+ax(7).Position(4)+1.5*margin;
ax(5).Position(2) = ax(8).Position(2)+ax(8).Position(4)+1.5*margin;
ax(6).Position(2) = ax(9).Position(2)+ax(9).Position(4)+1.5*margin;
ax(1).Position(2) = ax(4).Position(2)+ax(4).Position(4)+1.5*margin;
ax(2).Position(2) = ax(5).Position(2)+ax(5).Position(4)+1.5*margin;
ax(3).Position(2) = ax(6).Position(2)+ax(6).Position(4)+1.5*margin;

% left
ax(2).Position(1) = ax(1).Position(1)+ax(1).Position(3)+1.5*margin;
ax(3).Position(1) = ax(2).Position(1)+ax(2).Position(3)+1.5*margin;
ax(5).Position(1) = ax(4).Position(1)+ax(4).Position(3)+1.5*margin;
ax(6).Position(1) = ax(5).Position(1)+ax(5).Position(3)+1.5*margin;
ax(8).Position(1) = ax(7).Position(1)+ax(7).Position(3)+1.5*margin;
ax(9).Position(1) = ax(8).Position(1)+ax(8).Position(3)+1.5*margin;

% labels
letters = {'a','b','c','d','e','f','g','h','i'};
for n = 1:length(letters)
    t(n) = annotation('textbox');
    t(n).String = letters{n};
    t(n).FontSize = fontsize+2;
    t(n).FontWeight = 'bold';
    t(n).Interpreter = 'tex';
    t(n).Units = 'centimeters';
    t(n).Position = [ax(n).Position(1)-1.1*margin ax(n).Position(2)+h0 0.1 0.1];
    t(n).EdgeColor = 'w';
    t(n).HorizontalAlignment = 'left';
    t(n).VerticalAlignment = 'bottom';
end

% Freezing Point Depression
n = 11;
t(n) = annotation('textbox');
t(n).String = 'Freezing Point Depression';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(4).Position(2)-0.5 h0+2*0.5 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

% Convective Layer
n = 10;
t(n) = annotation('textbox');
t(n).String = 'Convective Layer';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(1).Position(2) h0 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

% Chloride-Doped Ice
n = 12;
t(n) = annotation('textbox');
t(n).String = 'Chloride-Doped Ice';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(7).Position(2) h0 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

f = gcf;
f.Color = 'w';
f.Units = 'centimeters';
width = 3*(1.5*margin+w0)+margin;
height = 3*(1.5*margin+h0);
f.Position(3:4) = [width height];