% radar_radiometer.m
% Generates Figure 3 using data generated by Tb_data.mat for the
% publication 
% 
% Wolfenbarger, N. S., Broome, A. L., Schroeder, D. M., Ermakov, A. I.,
% Bolton, S. J., and Blankenship, D. D. (2025). Passive Microwave
% Radiometry and Active Radar Sounding as Complementary Tools for
% Geophysical Investigations of Icy Ocean Worlds.

clear all; close all; clc

%% Add Paths
% Located at https://github.com/nwolfenb
addpath(genpath('..\..\IcyRF'))
addpath(genpath('..\..\BrineVolumeFraction'))

%% Defaults
fontsize = 8;
linewidth = 2;
interpreter = 'latex';
% brewermap available at MATLAB File Exchange
colors = brewermap(10,'Spectral');

%% Constants
rho = 940;
g = 1.315;
D = [1e-3 (1:1:100)]*1e3;
Ts = 100;

%% Temperature
figure
subplot(1,3,1)
N = 1e4;
Tm = 270;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax1 = gca;
ax1.YDir = 'reverse';
ax1.FontSize = fontsize;
ax1.TickLabelInterpreter = interpreter;
ax1.XTick = [Ts Tm];
ax1.XTickLabel = {'$100$';'$f(D)$'};
ax1.XLabel.String = 'Temperature, $T$ (K)';
ax1.XLabel.FontSize = fontsize;
ax1.XLabel.Interpreter = interpreter;
ax1.YLabel.String = 'Fractional Depth, $z/D$';
ax1.YLabel.FontSize = fontsize;
ax1.YLabel.Interpreter = interpreter;
ax1.XLim = [Ts-50 270+50];
ax1.YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;


%% Radiometer
load('Tb.mat')

subplot(1,3,2)
delta = Tb(1,:)-Tb(2,:);
plot(D/1e3,delta,'Color',[0 112 192]/255,'LineWidth',linewidth)
hold on
ax2 = gca;
ax2.FontSize = fontsize;
ax2.TickLabelInterpreter = interpreter;
ax2.XLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax2.XLabel.FontSize = fontsize;
ax2.XLabel.Interpreter = interpreter;
ax2.YLabel.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax2.YLabel.FontSize = fontsize;
ax2.YLabel.Interpreter = interpreter;
ax2.Title.String = '$Passive$ Microwave Radiometer';
ax2.Title.FontSize = fontsize;
ax2.Title.Interpreter = interpreter;
ax2.XLim = [0 100];
ax2.XTick = [0:20:100];
ax2.YLim = [-5 60];

disp(['Peak deltaTb = ',num2str(max(delta)),' K at D = ',num2str(D(delta==max(delta))/1e3),' km'])

%% Radar
f = 9e6;
subplot(1,3,3)
att = zeros(N,length(D));
for n = 1:length(D)
    P = rho*g*D(n);
    Tm = Tmelt(P);

    z = linspace(0,D(n),N);
    T = Ts*(Tm/Ts).^(z./D(n));

    eps_ice = ice_permittivity(T-273.15,f,0);
    [alpha, Na] = EMalpha(eps_ice,f);

    att(:,n) = 2*Na*1e3;
end
x = repmat(D,N,1)/1e3;
y = repmat(linspace(0,1,N)',1,length(D));

[C,h] = contour(x,y,att,[1e-1 1e0 1e1 1e2],'LineWidth',linewidth,'LineColor',[1 0 0]);
clabel(C,h,'Interpreter','latex','FontSize',fontsize,'Color',[1 0 0],...
    'labelspacing', 700)
hold on

p = plot([NaN NaN],[NaN NaN],'r');
ax3 = gca;
ax3.YDir = 'reverse';
ax3.FontSize = fontsize;
ax3.TickLabelInterpreter = interpreter;
ax3.XLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax3.XLabel.FontSize = fontsize;
ax3.XLabel.Interpreter = interpreter;
ax3.YLabel.String = 'Fractional Depth, $z/d$';
ax3.YLabel.FontSize = fontsize;
ax3.YLabel.Interpreter = interpreter;
ax3.Title.String = '$Active$ Radar Sounder';
ax3.Title.FontSize = fontsize;
ax3.Title.Interpreter = interpreter;
ax3.Layer = 'top';
ax3.XTick = 0:20:100;
leg = legend(p,'$2N_{\alpha}$ (dB/km)');
leg.ItemTokenSize = [15 15];
leg.Interpreter = interpreter;

%% Figure Formatting
% units
ax1.Units = 'centimeters';
ax2.Units = 'centimeters';
ax3.Units = 'centimeters';
cb.Units = 'centimeters';

% left
margin = 1;
ax1.Position(1) = margin;
ax2.Position(1) = margin;
ax3.Position(1) = margin;

% height
h0 = 4.25;
ax1.Position(4) = h0;
ax2.Position(4) = h0;
ax3.Position(4) = h0;

% width
w0 = 4.25;
ax1.Position(3) = w0;
ax2.Position(3) = w0;
ax3.Position(3) = w0;

% bottom
ax1.Position(2) = margin;
ax2.Position(2) = margin;
ax3.Position(2) = margin;

% left
ax2.Position(1) = ax1.Position(1)+ax1.Position(3)+1.25*margin;
ax3.Position(1) = ax2.Position(1)+ax2.Position(3)+1.25*margin;

% labels
ta = annotation('textbox');
ta.String = 'a';
ta.FontSize = fontsize+2;
ta.FontWeight = 'bold';
ta.Interpreter = 'tex';
ta.Units = 'centimeters';
ta.Position = [ax1.Position(1)-margin ax1.Position(2)+h0 0.1 0.1];
ta.EdgeColor = 'w';
ta.HorizontalAlignment = 'left';
ta.VerticalAlignment = 'bottom';

tb = annotation('textbox');
tb.String = 'b';
tb.FontSize = fontsize+2;
tb.FontWeight = 'bold';
tb.Interpreter = 'tex';
tb.Units = 'centimeters';
tb.Position = [ax2.Position(1)-margin ax2.Position(2)+h0 0.1 0.1];
tb.EdgeColor = 'w';
tb.HorizontalAlignment = 'left';
tb.VerticalAlignment = 'bottom';

tc = annotation('textbox');
tc.String = 'c';
tc.FontSize = fontsize+2;
tc.FontWeight = 'bold';
tc.Interpreter = 'tex';
tc.Units = 'centimeters';
tc.Position = [ax3.Position(1)-margin ax3.Position(2)+h0 0.1 0.1];
tc.EdgeColor = 'w';
tc.HorizontalAlignment = 'left';
tc.VerticalAlignment = 'bottom';

f = gcf;
f.Color = 'w';
f.Units = 'centimeters';
width = 3*(1.25*margin+w0);
height = (1.5*margin+h0);
f.Position(3:4) = [width height];
