% radiometer_constraints.m
% Generates Figure 4 using data generated by Tb_data.mat for the
% publication 
% 
% Wolfenbarger, N. S., Broome, A. L., Schroeder, D. M., Ermakov, A. I.,
% Bolton, S. J., and Blankenship, D. D. (2025). Passive Microwave
% Radiometry and Active Radar Sounding as Complementary Tools for
% Geophysical Investigations of Icy Ocean Worlds.

clear all; close all; clc

%% Defaults
fontsize = 8;
linewidth = 2;
interpreter = 'latex';

%% Constants
Ts = 100;

%% Freezing Point Depression
% Temperature Profile
p = 4;
subplot(3,3,p)
N = 1e4;
Tm = 250;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$f(D)-\Delta T_f$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

% Brightness Temperature Difference Contour
p = 5;
subplot(3,3,p)
load('Tb_deltaTm.mat')
delta_Tb = squeeze(Tb(1,:,:)-Tb(2,:,:));
x = repmat(D'/1e3,1,length(deltaTm));
y = repmat(deltaTm,length(D),1);


[C,h] = contour(y.',x.',delta_Tb.',[10:5:40],'LineWidth',linewidth,'LineColor',[0 112 192]/255);
clabel(C,h,'Interpreter','latex','FontSize',fontsize,'Color',[0 112 192]/255,...
    'BackgroundColor','w','LabelSpacing', 700)
hold on

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Freezing Point Depression, $\Delta T_f$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLim = [0 100];
ax(p).YTick = 0:20:100;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
box on


% Compatible Ice Shell Thickness
p = 6;
subplot(3,3,p)
deltaTb_vec = [0:0.1:50];

load('Tb_deltaTm.mat')
deltaTb_deltaTm = squeeze(Tb(1,:,:)-Tb(2,:,:));
C = contourc(deltaTm,D'/1e3,deltaTb_deltaTm,deltaTb_vec);
S = contourdata(C);

for n = 1:length(S)
    plot(S(n).level*ones(S(n).numel,1),S(n).ydata,'Color',[1 1 1]*0.8,...
        'LineWidth',linewidth)
    hold on
end

load('Tb.mat')
deltaTb = squeeze(Tb(1,:,:)-Tb(2,:,:));
[deltaTb_max,ind] = max(deltaTb);
D_vec1 = interp1(deltaTb(1:ind),D(1:ind)/1e3,deltaTb_vec);
D_vec2 = interp1(deltaTb(ind:end),D(ind:end)/1e3,deltaTb_vec);
plot(deltaTb_vec,D_vec1,'Color',[0 112 192]/255,'LineWidth',linewidth)
plot(deltaTb_vec,D_vec2,'Color',[0 112 192]/255,'LineWidth',linewidth)

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [0 50];
ax(p).Layer = 'Top';

%% Warm Convective Layer
% Temperature Profile
p = 1;
subplot(3,3,p)
Tm = 260;
N = 1e4/2;
z = linspace(0,1/2,N)';
T = Ts*(Tm/Ts).^(z/(1/2));
z = [z; linspace(1/2,1,N)'];
z = flipud(z);
T = [T; ones(size(T))*Tm];

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$260$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];
ax(p).YTick = [0 1];
ax(p).YTickLabel = cellstr(num2str(([1 0])'));

t1 = text(Ts,1,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,1,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

delta_x = 15;
delta_y = 0.025;

ar = annotation('doublearrow');
ar.Parent = ax(p);
ar.X = [Tm-delta_x Tm-delta_x];
ar.Y = [0+delta_y 0.5-delta_y];
ar.Head1Length = 5;
ar.Head2Length = 5;
ar.Head1Width = 5;
ar.Head2Width = 5;
ar.Head1Style = 'plain';
ar.Head2Style = 'plain';
ar.LineWidth = linewidth/2;

txt = text(Tm-delta_x,0.25,'$d_{conv}/D$ ');
txt.FontSize = fontsize;
txt.HorizontalAlignment = 'right';
txt.Interpreter = interpreter;

% Brightness Temperature Difference Contour
p = 2;
subplot(3,3,p)
load('Tb_fconv_260.mat')
delta_Tb = squeeze(Tb(1,:,:)-Tb(2,:,:));
x = repmat(D'/1e3,1,length(fconv));
y = repmat(fconv,length(D),1);


[C,h] = contour(y.',x.',delta_Tb.',[10:5:40],'LineWidth',linewidth,'LineColor',[0 112 192]/255);
clabel(C,h,'Interpreter','latex','FontSize',fontsize,'Color',[0 112 192]/255,...
    'BackgroundColor','w','LabelSpacing', 700)
hold on

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = 'Convective Fraction, $d_{conv}/D$';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).XTick = 0:0.2:1;
ax(p).YLim = [0 100];
ax(p).YTick = 0:20:100;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
box on


% Ice Shell Thickness Uncertainty
p = 3;
subplot(3,3,p)
deltaTb_vec = [0:0.1:50];

load('Tb_fconv_260.mat')
deltaTb_fconv_260 = squeeze(Tb(1,:,:)-Tb(2,:,:));
C = contourc(fconv,D'/1e3,deltaTb_fconv_260,deltaTb_vec);
S = contourdata(C);

for n = 1:length(S)
    plot(S(n).level*ones(S(n).numel,1),S(n).ydata,'Color',[1 1 1]*0.8,...
        'LineWidth',linewidth)
    hold on
end

load('Tb.mat')
deltaTb = squeeze(Tb(1,:,:)-Tb(2,:,:));
[deltaTb_max,ind] = max(deltaTb);
D_vec1 = interp1(deltaTb(1:ind),D(1:ind)/1e3,deltaTb_vec);
D_vec2 = interp1(deltaTb(ind:end),D(ind:end)/1e3,deltaTb_vec);
plot(deltaTb_vec,D_vec1,'Color',[0 112 192]/255,'LineWidth',linewidth)
plot(deltaTb_vec,D_vec2,'Color',[0 112 192]/255,'LineWidth',linewidth)

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [0 50];
ax(p).Layer = 'Top';

%% Chloride-Doped Ice
% Temperature Profile
p = 7;
subplot(3,3,p)
N = 1e4;
Tm = 270;
z = linspace(0,1,N)';
T = Ts*(Tm/Ts).^(z);

plot(T,z,'k','LineWidth',linewidth)
ax(p) = gca;
ax(p).YDir = 'reverse';
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XTick = [Ts Tm];
ax(p).XTickLabel = {'$100$';'$f(D)$'};
ax(p).XLabel.String = 'Temperature, $T$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Fractional Depth, $z/D$';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [Ts-50 270+50];
ax(p).YLim = [0 1];

t1 = text(Ts,0,'$T_s$');
t1.HorizontalAlignment='center';
t1.VerticalAlignment ='bottom';
t1.FontSize = fontsize;
t1.Interpreter = interpreter;

t2 = text(Tm,0,'$T_m$');
t2.HorizontalAlignment='center';
t2.VerticalAlignment ='bottom';
t2.FontSize = fontsize;
t2.Interpreter = interpreter;

% Brightness Temperature Difference Contour
p = 8;
subplot(3,3,p)
load('Tb_Cl.mat')
delta_Tb = squeeze(Tb(1,:,:)-Tb(2,:,:));
x = repmat(D'/1e3,1,length(uMCl));
y = repmat(uMCl,length(D),1);


[C,h] = contour(y.',x.',delta_Tb.',[10:5:40],'LineWidth',linewidth,'LineColor',[0 112 192]/255);
clabel(C,h,'Interpreter','latex','FontSize',fontsize,'Color',[0 112 192]/255,...
    'BackgroundColor','w','LabelSpacing', 700)
hold on

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String =  'Ice Chlorinity, [Cl$^{-}$] ($\mu$M)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLim = [0 100];
ax(p).YTick = 0:20:100;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).Title.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).Title.FontSize = fontsize;
ax(p).Title.Interpreter = interpreter;
box on


% Ice Shell Thickness Uncertainty
p = 9;
subplot(3,3,p)
deltaTb_vec = [0:0.1:50];

load('Tb_Cl.mat')
deltaTb_Cl = squeeze(Tb(1,:,:)-Tb(2,:,:));
C = contourc(uMCl,D'/1e3,deltaTb_Cl,deltaTb_vec);
S = contourdata(C);

for n = 1:length(S)
    plot(S(n).level*ones(S(n).numel,1),S(n).ydata,'Color',[1 1 1]*0.8,'LineWidth',linewidth)
    hold on
end

load('Tb.mat')
deltaTb = squeeze(Tb(1,:,:)-Tb(2,:,:));
[deltaTb_max,ind] = max(deltaTb);
D_vec1 = interp1(deltaTb(1:ind),D(1:ind)/1e3,deltaTb_vec);
D_vec2 = interp1(deltaTb(ind:end),D(ind:end)/1e3,deltaTb_vec);
plot(deltaTb_vec,D_vec1,'Color',[0 112 192]/255,'LineWidth',linewidth)
plot(deltaTb_vec,D_vec2,'Color',[0 112 192]/255,'LineWidth',linewidth)

ax(p) = gca;
ax(p).FontSize = fontsize;
ax(p).TickLabelInterpreter = interpreter;
ax(p).XLabel.String = '$\Delta \mathcal{T}_{ice,0.6/1.2}=\mathcal{T}_{ice,0.6}-\mathcal{T}_{ice,1.2}$ (K)';
ax(p).XLabel.FontSize = fontsize;
ax(p).XLabel.Interpreter = interpreter;
ax(p).YLabel.String = 'Ice Shell Thickness, $D$ (km)';
ax(p).YLabel.FontSize = fontsize;
ax(p).YLabel.Interpreter = interpreter;
ax(p).XLim = [0 50];
ax(p).Layer = 'Top';

%% Figure Formatting
%  [left bottom width height]

% units
for p = 1:length(ax)
ax(p).Units = 'centimeters';
end

% left
margin = 1;
ax(1).Position(1) = 1.5*margin;
ax(4).Position(1) = 1.5*margin;
ax(7).Position(1) = 1.5*margin;

% height
h0 = 4.25;
for p = 1:length(ax)
ax(p).Position(4) = h0;
end

% width
w0 = 4.25;
for p = 1:length(ax)
ax(p).Position(3) = w0;
end

% bottom
ax(7).Position(2) = margin;
ax(8).Position(2) = margin;
ax(9).Position(2) = margin;
ax(4).Position(2) = ax(7).Position(2)+ax(7).Position(4)+1.5*margin;
ax(5).Position(2) = ax(8).Position(2)+ax(8).Position(4)+1.5*margin;
ax(6).Position(2) = ax(9).Position(2)+ax(9).Position(4)+1.5*margin;
ax(1).Position(2) = ax(4).Position(2)+ax(4).Position(4)+1.5*margin;
ax(2).Position(2) = ax(5).Position(2)+ax(5).Position(4)+1.5*margin;
ax(3).Position(2) = ax(6).Position(2)+ax(6).Position(4)+1.5*margin;

% left
ax(2).Position(1) = ax(1).Position(1)+ax(1).Position(3)+1.25*margin;
ax(3).Position(1) = ax(2).Position(1)+ax(2).Position(3)+1.25*margin;
ax(5).Position(1) = ax(4).Position(1)+ax(4).Position(3)+1.25*margin;
ax(6).Position(1) = ax(5).Position(1)+ax(5).Position(3)+1.25*margin;
ax(8).Position(1) = ax(7).Position(1)+ax(7).Position(3)+1.25*margin;
ax(9).Position(1) = ax(8).Position(1)+ax(8).Position(3)+1.25*margin;

% labels
letters = {'a','b','c','d','e','f','g','h','i'};
for n = 1:length(letters)
    t(n) = annotation('textbox');
    t(n).String = letters{n};
    t(n).FontSize = fontsize+2;
    t(n).FontWeight = 'bold';
    t(n).Interpreter = 'tex';
    t(n).Units = 'centimeters';
    t(n).Position = [ax(n).Position(1)-margin ax(n).Position(2)+h0 0.1 0.1];
    t(n).EdgeColor = 'w';
    t(n).HorizontalAlignment = 'left';
    t(n).VerticalAlignment = 'bottom';
end

% Freezing Point Depression
n = 11;
t(n) = annotation('textbox');
t(n).String = 'Freezing Point Depression';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(4).Position(2)-0.5 h0+2*0.5 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

% Convective Layer
n = 10;
t(n) = annotation('textbox');
t(n).String = 'Convective Layer';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(1).Position(2) h0 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

% Chloride-Doped Ice
n = 12;
t(n) = annotation('textbox');
t(n).String = 'Chloride-Doped Ice';
t(n).FontSize = fontsize+2;
t(n).FontWeight = 'bold';
t(n).Interpreter = 'tex';
t(n).Units = 'centimeters';
t(n).Position = [0 ax(7).Position(2) h0 0.1];
t(n).EdgeColor = 'w';
t(n).HorizontalAlignment = 'center';
t(n).VerticalAlignment = 'top';
t(n).Rotation = 90;

f = gcf;
f.Color = 'w';
f.Units = 'centimeters';
width = 3*(1.25*margin+w0)+margin;
height = 3*(1.5*margin+h0);
f.Position(3:4) = [width height];
